// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPD3O3cUdCNgG39K2eAtAgrvNbJuz7c4',
    appId: '1:647814031378:web:94fd6c79d16aa5cbd3d0cb',
    messagingSenderId: '647814031378',
    projectId: '',
    authDomain: '',
    storageBucket: '',
    measurementId: 'G-Y55RSFL5PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcYCPyJKPbaSnY54bE_sjHpe8Xv3BJ4cc',
    appId: '1:647814031378:android:3b3038a6c1a6d645d3d0cb',
    messagingSenderId: '647814031378',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZi4I-z5Lym1S8Z9V3h4PdBbGVrpecnfg',
    appId: '1:647814031378:ios:834cdb2d24590aa4d3d0cb',
    messagingSenderId: '647814031378',
    projectId: '',
    storageBucket: '',
    androidClientId:
        '647814031378-jrjpb6o016m5v2pmspt6nb998cvk634a.apps.googleusercontent.com',
    iosClientId:
        '647814031378-em9cb34qh7fdsmnju8uirgthft0iurbo.apps.googleusercontent.com',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZi4I-z5Lym1S8Z9V3h4PdBbGVrpecnfg',
    appId: '1:647814031378:ios:834cdb2d24590aa4d3d0cb',
    messagingSenderId: '647814031378',
    projectId: '',
    storageBucket: '',
    androidClientId:
        '647814031378-jrjpb6o016m5v2pmspt6nb998cvk634a.apps.googleusercontent.com',
    iosClientId:
        '647814031378-em9cb34qh7fdsmnju8uirgthft0iurbo.apps.googleusercontent.com',
    iosBundleId: '',
  );
}
